name: CI Pipeline for Ghost

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: SSH to server, clone and run docker-compose
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        password: ${{ secrets.SERVER_PASSWORD }}
        script: |
          mkdir -p ~/vtv-index
          
          cd ~/vtv-index
          
          if [ -d .git ]; then
            git pull
          else
            git clone git@github.com:CaptainHoangLe/vtv-index.git .
          fi
          
          docker compose down
          docker compose up -d
          
          echo "Deployment completed successfully!"