name: CI Pipeline for Ghost

on:
  push:
    branches: [main]

env:
  IMAGE_NAME: captainhoangle/vtv-index

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Extract Git short SHA for version
      id: version
      run: echo "sha=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

    - name: Build Docker image
      run: |
        docker build -t $IMAGE_NAME:latest -t $IMAGE_NAME:${{ steps.version.outputs.sha }} .

    - name: Push Docker image to Docker Hub
      run: |
        docker push $IMAGE_NAME:latest
        docker push $IMAGE_NAME:${{ steps.version.outputs.sha }}

    outputs:
      sha: ${{ steps.version.outputs.sha }}

  deploy-to-server:
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
    - name: SSH to server and pull latest image
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        password: ${{ secrets.SERVER_PASSWORD }}
        script: |
          # Create or update docker-compose.yml
          cat > ~/docker-compose.yml <<EOF
          version: '3'
          services:
            vtv-index:
              image: ${{ env.IMAGE_NAME }}:latest
              ports:
                - "2368:2368"
              volumes:
                - /home/${{ secrets.SERVER_USER }}/ghost/content:/app/content
              restart: always
          EOF
          
          # Deploy with docker compose
          docker compose down
          docker compose pull
          docker compose up -d
